### ISSUE TITLE
rpaframework not supported using Python 3.9

### ISSUE THREAD

**Issue by weh2017** [robocorp/rpaframework#142]
I've tried to upgrade Python to 3.9.2 and install the Robot Framework - rpaframework ver. 7.5.0

Error message that I've encountered.  "Keyword" not found.

So what I did, I've installed back Python 3.8.6 and rpaframework ver. 7.5.0 and the scripts, it works fine.

**Comment by osrjv** [comment]
Hi, thanks for the report.

We officially only support Python 3.6 to 3.8, and there's an issue for tracking problems with 3.9: https://github.com/robocorp/rpaframework/issues/69. However, it _should_ currently work. Keywords not being found would indicate that something didn't install correctly.

Could you answer these questions:
- What operating system are you using?
- What tool are you using to install dependencies?
- Were there some errors during rpaframework installation when running 3.9.2?

**Comment by SamArmand** [comment]
If I update python in the conda.yaml to 3.9.2, I get this:

```
Stderr: ####  Progress: 0/6  [try use existing live same environment?] 70cabda0-f9bd-cc2f-265d-4b64e5bf37d4
FINAL union conda environment descriptor:
---
channels:
- conda-forge
dependencies:
- python=3.9.2
- rpaframework==9.5.0
---
####  Progress: 1/6  [environment key is: cf023033850bfa1a]
####  Progress: 2/6  [try clone existing same template to live, key: cf023033850bfa1a]
####  Progress: 3/6  [try create new environment from scratch]
Fatal [Micromamba]: exit status 1
Retry! First try failed ... now retrying with debug and force options!
```

**Comment by pratapslair** [comment]
Hi I am also facing the same issue. I've installed Python 3.9 in Win10 x64. I used pip directly.

**Comment by osrjv** [comment]
@pratapslair, can you share the entire log from pip when you attempt the install?

**Comment by pratapslair** [comment]
> @pratapslair, can you share the entire log from pip when you attempt the install?

I was able to install it with Python38 using Anaconda. the issue is resolved.

**Comment by cmin764** [comment]
We officially support **3.9.13** Python now.

**Comment by Revathy0294** [comment]
> @pratapslair, can you share the entire log from pip when you attempt the install?
Hi I have python version 3.9 .12 I tried to install robot framework using command prompt and anaconda. I still get the same error
These are the commands I used
a) pip install wxPython
b)pip install robotframework
c)pip install robotframework-ride
I am getting error ,
Does this version support robot frame work ?

base) C:\Users\revathy.ganesh.INTERNAL>pip install robotframework
Collecting robotframework
  Using cached robotframework-6.0-py3-none-any.whl (657 kB)
Installing collected packages: robotframework
Successfully installed robotframework-6.0

(base) C:\Users\revathy.ganesh.INTERNAL>pip install robotframework-ride
Collecting robotframework-ride
  Using cached robotframework-ride-1.7.4.2.tar.gz (846 kB)
Collecting wxPython<=4.0.7.post2
  Using cached wxPython-4.0.7.post2.tar.gz (68.9 MB)
Collecting PyPubSub
  Using cached Pypubsub-4.0.3-py3-none-any.whl (61 kB)
Requirement already satisfied: Pygments in c:\users\revathy.ganesh.internal\anaconda3\lib\site-packages (from robotframework-ride) (2.11.2)
Requirement already satisfied: Pywin32 in c:\users\revathy.ganesh.internal\anaconda3\lib\site-packages (from robotframework-ride) (302)
Requirement already satisfied: pillow in c:\users\revathy.ganesh.internal\anaconda3\lib\site-packages (from wxPython<=4.0.7.post2->robotframework-ride) (9.0.1)
Requirement already satisfied: six in c:\users\revathy.ganesh.internal\anaconda3\lib\site-packages (from wxPython<=4.0.7.post2->robotframework-ride) (1.16.0)
Requirement already satisfied: numpy in c:\users\revathy.ganesh.internal\anaconda3\lib\site-packages (from wxPython<=4.0.7.post2->robotframework-ride) (1.21.5)
Building wheels for collected packages: robotframework-ride, wxPython
  Building wheel for robotframework-ride (setup.py) ... done
  Created wheel for robotframework-ride: filename=robotframework_ride-1.7.4.2-py3-none-any.whl size=951030 sha256=99ce96dae5a1d162dd6a37585cd85b313dd27d08e49996d2047612602854508e
  Stored in directory: c:\users\revathy.ganesh.internal\appdata\local\pip\cache\wheels\2e\1b\b3\aff59fc3c80a758e521514ea7c4cc7b7fc00f9e1ee285876bf
  Building wheel for wxPython (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\revathy.ganesh.INTERNAL\Anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\revathy.ganesh.INTERNAL\\AppData\\Local\\Temp\\pip-install-mx6zx4vk\\wxpython_2f95a3735e80494582cb3273558ccecc\\setup.py'"'"'; __file__='"'"'C:\\Users\\revathy.ganesh.INTERNAL\\AppData\\Local\\Temp\\pip-install-mx6zx4vk\\wxpython_2f95a3735e80494582cb3273558ccecc\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\revathy.ganesh.INTERNAL\AppData\Local\Temp\pip-wheel-cwqr7sgv'
       cwd: C:\Users\revathy.ganesh.INTERNAL\AppData\Local\Temp\pip-install-mx6zx4vk\wxpython_2f95a3735e80494582cb3273558ccecc\
  Complete output (49 lines):
  C:\Users\revathy.ganesh.INTERNAL\Anaconda3\lib\site-packages\setuptools\dist.py:757: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
    warnings.warn(
  C:\Users\revathy.ganesh.INTERNAL\Anaconda3\lib\site-packages\setuptools\dist.py:303: DistDeprecationWarning: use_2to3 is ignored.
    warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
  running bdist_wheel
  running build
  Will build using: "C:\Users\revathy.ganesh.INTERNAL\Anaconda3\python.exe"
  3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
  Python's architecture is 64bit
  cfg.VERSION: 4.0.7.post2

  Running command: build
  Running command: build_wx
  Command '"C:\Users\revathy.ganesh.INTERNAL\Anaconda3\python.exe" -c "import distutils.msvc9compiler as msvc; mc = msvc.MSVCCompiler(); mc.initialize(); print(mc.cc)"' failed with exit code 1.
  Traceback (most recent call last):

    File "<string>", line 1, in <module>

    File "C:\Users\revathy.ganesh.INTERNAL\Anaconda3\lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 371, in initialize

      vc_env = query_vcvarsall(VERSION, plat_spec)

    File "C:\Users\revathy.ganesh.INTERNAL\Anaconda3\lib\site-packages\setuptools\msvc.py", line 140, in msvc9_query_vcvarsall

      return EnvironmentInfo(arch, ver).return_env()

    File "C:\Users\revathy.ganesh.INTERNAL\Anaconda3\lib\site-packages\setuptools\msvc.py", line 1740, in return_env

      [self.VCIncludes,

    File "C:\Users\revathy.ganesh.INTERNAL\Anaconda3\lib\site-packages\setuptools\msvc.py", line 1282, in VCIncludes

      return [join(self.si.VCInstallDir, 'Include'),

    File "C:\Users\revathy.ganesh.INTERNAL\Anaconda3\lib\site-packages\setuptools\msvc.py", line 840, in VCInstallDir

      raise distutils.errors.DistutilsPlatformError(msg)

  distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.1 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  Finished command: build_wx (0m1.263s)
  Finished command: build (0m1.263s)
  WARNING: Building this way assumes that all generated files have been
  generated already.  If that is not the case then use build.py directly
  to generate the source and perform the build stage.  You can use
  --skip-build with the bdist_* or install commands to avoid this
  message and the wxWidgets and Phoenix build steps in the future.

  "C:\Users\revathy.ganesh.INTERNAL\Anaconda3\python.exe" -u build.py build
  Command '"C:\Users\revathy.ganesh.INTERNAL\Anaconda3\python.exe" -u build.py build' failed with exit code 1.
  ----------------------------------------
  ERROR: Failed building wheel for wxPython
  Running setup.py clean for wxPython
Successfully built robotframework-ride
Failed to build wxPython
Installing collected packages: wxPython, PyPubSub, robotframework-ride
  Attempting uninstall: wxPython
    Found existing installation: wxPython 4.2.0
    Uninstalling wxPython-4.2.0:
      Successfully uninstalled wxPython-4.2.0
    Running setup.py install for wxPython ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\revathy.ganesh.INTERNAL\Anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\revathy.ganesh.INTERNAL\\AppData\\Local\\Temp\\pip-install-mx6zx4vk\\wxpython_2f95a3735e80494582cb3273558ccecc\\setup.py'"'"'; __file__='"'"'C:\\Users\\revathy.ganesh.INTERNAL\\AppData\\Local\\Temp\\pip-install-mx6zx4vk\\wxpython_2f95a3735e80494582cb3273558ccecc\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\revathy.ganesh.INTERNAL\AppData\Local\Temp\pip-record-baswz_wn\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\revathy.ganesh.INTERNAL\Anaconda3\Include\wxPython'
         cwd: C:\Users\revathy.ganesh.INTERNAL\AppData\Local\Temp\pip-install-mx6zx4vk\wxpython_2f95a3735e80494582cb3273558ccecc\
    Complete output (51 lines):
    C:\Users\revathy.ganesh.INTERNAL\Anaconda3\lib\site-packages\setuptools\dist.py:757: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
      warnings.warn(
    C:\Users\revathy.ganesh.INTERNAL\Anaconda3\lib\site-packages\setuptools\dist.py:303: DistDeprecationWarning: use_2to3 is ignored.
      warnings.warn(f"{attr} is ignored.", DistDeprecationWarning)
    running install
    C:\Users\revathy.ganesh.INTERNAL\Anaconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    Will build using: "C:\Users\revathy.ganesh.INTERNAL\Anaconda3\python.exe"
    3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
    Python's architecture is 64bit
    cfg.VERSION: 4.0.7.post2

    Running command: build
    Running command: build_wx
    Command '"C:\Users\revathy.ganesh.INTERNAL\Anaconda3\python.exe" -c "import distutils.msvc9compiler as msvc; mc = msvc.MSVCCompiler(); mc.initialize(); print(mc.cc)"' failed with exit code 1.
    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "C:\Users\revathy.ganesh.INTERNAL\Anaconda3\lib\site-packages\setuptools\_distutils\msvc9compiler.py", line 371, in initialize

        vc_env = query_vcvarsall(VERSION, plat_spec)

      File "C:\Users\revathy.ganesh.INTERNAL\Anaconda3\lib\site-packages\setuptools\msvc.py", line 140, in msvc9_query_vcvarsall

        return EnvironmentInfo(arch, ver).return_env()

      File "C:\Users\revathy.ganesh.INTERNAL\Anaconda3\lib\site-packages\setuptools\msvc.py", line 1740, in return_env

        [self.VCIncludes,

      File "C:\Users\revathy.ganesh.INTERNAL\Anaconda3\lib\site-packages\setuptools\msvc.py", line 1282, in VCIncludes

        return [join(self.si.VCInstallDir, 'Include'),

      File "C:\Users\revathy.ganesh.INTERNAL\Anaconda3\lib\site-packages\setuptools\msvc.py", line 840, in VCInstallDir

        raise distutils.errors.DistutilsPlatformError(msg)

    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.1 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    Finished command: build_wx (0m1.292s)
    Finished command: build (0m1.292s)
    WARNING: Building this way assumes that all generated files have been
    generated already.  If that is not the case then use build.py directly
    to generate the source and perform the build stage.  You can use
    --skip-build with the bdist_* or install commands to avoid this
    message and the wxWidgets and Phoenix build steps in the future.

    "C:\Users\revathy.ganesh.INTERNAL\Anaconda3\python.exe" -u build.py build
    Command '"C:\Users\revathy.ganesh.INTERNAL\Anaconda3\python.exe" -u build.py build' failed with exit code 1.
    ----------------------------------------
  Rolling back uninstall of wxPython
  Moving to c:\users\revathy.ganesh.internal\anaconda3\lib\site-packages\wx\
   from C:\Users\revathy.ganesh.INTERNAL\Anaconda3\Lib\site-packages\~x
  Moving to c:\users\revathy.ganesh.internal\anaconda3\lib\site-packages\wxpython-4.2.0.dist-info\
   from C:\Users\revathy.ganesh.INTERNAL\Anaconda3\Lib\site-packages\~xpython-4.2.0.dist-info
  Moving to c:\users\revathy.ganesh.internal\anaconda3\scripts\helpviewer.exe
   from C:\Users\revathy.ganesh.INTERNAL\AppData\Local\Temp\pip-uninstall-odvga215\helpviewer.exe
  Moving to c:\users\revathy.ganesh.internal\anaconda3\scripts\img2png.exe
   from C:\Users\revathy.ganesh.INTERNAL\AppData\Local\Temp\pip-uninstall-odvga215\img2png.exe
  Moving to c:\users\revathy.ganesh.internal\anaconda3\scripts\img2py.exe
   from C:\Users\revathy.ganesh.INTERNAL\AppData\Local\Temp\pip-uninstall-odvga215\img2py.exe
  Moving to c:\users\revathy.ganesh.internal\anaconda3\scripts\img2xpm.exe
   from C:\Users\revathy.ganesh.INTERNAL\AppData\Local\Temp\pip-uninstall-odvga215\img2xpm.exe
  Moving to c:\users\revathy.ganesh.internal\anaconda3\scripts\pycrust.exe
   from C:\Users\revathy.ganesh.INTERNAL\AppData\Local\Temp\pip-uninstall-odvga215\pycrust.exe
  Moving to c:\users\revathy.ganesh.internal\anaconda3\scripts\pyshell.exe
   from C:\Users\revathy.ganesh.INTERNAL\AppData\Local\Temp\pip-uninstall-odvga215\pyshell.exe
  Moving to c:\users\revathy.ganesh.internal\anaconda3\scripts\pyslices.exe
   from C:\Users\revathy.ganesh.INTERNAL\AppData\Local\Temp\pip-uninstall-odvga215\pyslices.exe
  Moving to c:\users\revathy.ganesh.internal\anaconda3\scripts\pyslicesshell.exe
   from C:\Users\revathy.ganesh.INTERNAL\AppData\Local\Temp\pip-uninstall-odvga215\pyslicesshell.exe
  Moving to c:\users\revathy.ganesh.internal\anaconda3\scripts\pywxrc.exe
   from C:\Users\revathy.ganesh.INTERNAL\AppData\Local\Temp\pip-uninstall-odvga215\pywxrc.exe
  Moving to c:\users\revathy.ganesh.internal\anaconda3\scripts\wxdemo.exe
   from C:\Users\revathy.ganesh.INTERNAL\AppData\Local\Temp\pip-uninstall-odvga215\wxdemo.exe
  Moving to c:\users\revathy.ganesh.internal\anaconda3\scripts\wxdocs.exe
   from C:\Users\revathy.ganesh.INTERNAL\AppData\Local\Temp\pip-uninstall-odvga215\wxdocs.exe
  Moving to c:\users\revathy.ganesh.internal\anaconda3\scripts\wxget.exe
   from C:\Users\revathy.ganesh.INTERNAL\AppData\Local\Temp\pip-uninstall-odvga215\wxget.exe
ERROR: Command errored out with exit status 1: 'C:\Users\revathy.ganesh.INTERNAL\Anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\revathy.ganesh.INTERNAL\\AppData\\Local\\Temp\\pip-install-mx6zx4vk\\wxpython_2f95a3735e80494582cb3273558ccecc\\setup.py'"'"'; __file__='"'"'C:\\Users\\revathy.ganesh.INTERNAL\\AppData\\Local\\Temp\\pip-install-mx6zx4vk\\wxpython_2f95a3735e80494582cb3273558ccecc\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\revathy.ganesh.INTERNAL\AppData\Local\Temp\pip-record-baswz_wn\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\revathy.ganesh.INTERNAL\Anaconda3\Include\wxPython' Check the logs for full command output.

(base) C:\Users\revathy.ganesh.INTERNAL>python
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
